print(3>=3)
#print(‘hello’, ‘how’, ‘are’, ‘you’)
#print(‘hello’, ‘how’, ‘are’, ‘you’ + ‘-‘ * 4)
#print(‘hello-‘ + ‘how-are-you’)
#print(‘hello’ + ‘-‘ + ‘how’ + ‘-‘ + ‘are’ + ‘you’)
a=round(-0.7)
print(a)
#b=round(-1.5)
#c=a-b
#print(a)
#print(b)
#print(c)
#round(0.5)
d=round(0.5)-round(-0.5)
print(d)
#print('hello' + '-' + 'how' + '-' + 'are' + 'you')
#print('hello-' + 'how-are-you')
